---
- name: Installing Sonarr
  docker_container:
    name: sonarr
    image: "ghcr.io/linuxserver/sonarr"
    pull: yes
    networks:
      - name: main_network
    state: "started"
    env:
      "PUID": "1000"
      "PGID": "1000"
      "TZ": "{{ timezone }}"
    volumes:
      - "/etc/localtime:/etc/localtime"
      - "{{ sonarr_config_dir }}:/config"
      - "{{ hdd2 }}/Media/TV:/tv"
      - "{{ hdd2 }}/Downloads:/downloads"
    restart_policy: unless-stopped
    ports:
      - "{{ sonarr_port }}:8989"
    memory: "{{ sonarr_memory }}"
    labels:
      "flame.type": "application"
      "flame.name": Sonarr
      "flame.url": "{{ server_ip }}:{{ sonarr_port }}"
      "flame.icon": "television-classic"
