---
- hosts: all
  become: true

  roles:
    ###
    # Essentials
    ###
    - role: system
      tags:
        - system

    - role: docker
      tags:
        - docker

    ###
    # 42 School
    ###
    - role: school42
      tags:
        - school42

    ###
    # Containers
    ###

    - role: containers/system/portainer
      become: false
      tags:
        - containers
        - portainer

    - role: containers/system/cloudflareddns
      become: false
      tags:
        - containers
        - cloudflareddns

    - role: containers/system/watchtower
      become: false
      tags:
        - containers
        - watchtower

    - role: containers/system/flame
      become: false
      tags:
        - containers
        - flame

    - role: containers/system/authelia
      become: false
      tags:
        - containers
        - authelia

    - role: containers/system/pihole
      become: false
      tags:
        - containers
        - pihole

    - role: containers/services/vaultwarden
      become: false
      tags:
        - containers
        - vaultwarden

    - role: containers/services/photoprism
      become: false
      tags:
        - containers
        - photoprism

    - role: containers/services/nginxproxy
      become: false
      tags:
        - containers
        - nginxproxy

    - role: containers/services/guacamole
      become: false
      tags:
        - containers
        - guacamole

    - role: containers/services/calibre
      become: false
      tags:
        - containers
        - calibre

    - role: containers/services/nextcloud
      become: false
      tags:
        - containers
        - nextcloud

    - role: containers/services/gitea
      become: false
      tags:
        - containers
        - gitea

    - role: containers/services/home_assistant
      become: false
      tags:
        - containers
        - home_assistant

    - role: containers/media/jellyfin
      become: false
      tags:
        - containers
        - media
        - jellyfin

    - role: containers/media/plex
      become: false
      tags:
        - containers
        - media
        - plex

    - role: containers/media/prowlarr
      become: false
      tags:
        - containers
        - media
        - prowlarr

    - role: containers/media/radarr
      become: false
      tags:
        - containers
        - media
        - radarr

    - role: containers/media/sonarr
      become: false
      tags:
        - containers
        - media
        - sonarr

    - role: containers/media/deluge
      become: false
      tags:
        - containers
        - media
        - deluge

    - role: containers/media/flaresolverr
      become: false
      tags:
        - containers
        - media
        - flaresolverr

    - role: containers/media/jellyseerr
      become: false
      tags:
        - containers
        - media
        - jellyseerr

    - role: containers/media/bazarr
      become: false
      tags:
        - containers
        - media
        - bazarr

    - role: containers/media/searcharr
      become: false
      tags:
        - containers
        - media
        - searcharr

    ###
    # Security
    ###
    # - role: security/crowdsec
    #   tags:
    #     - security
    #     - crowdsec

    ###
    # Post
    ###
    - role: post
      tags:
        - post
