---
- hosts: all
  become: true

  roles:
    ###
    # Essentials
    ###
    - role: system
      tags:
        - system

    - role: docker
      tags:
        - docker

    ###
    # 42 School
    ###
    - role: school42
      tags:
        - school42

    ###
    # Containers
    ###
    # - role: containers/homer
    #   become: false
    #   tags:
    #     - containers
    #     - homer

    - role: containers/system/portainer
      become: false
      tags:
        - containers
        - portainer

    - role: containers/system/cloudflareddns
      become: false
      tags:
        - containers
        - cloudflareddns

    - role: containers/system/watchtower
      become: false
      tags:
        - containers
        - watchtower

    - role: containers/system/flame
      become: false
      tags:
        - containers
        - flame

    - role: containers/system/authelia
      become: false
      tags:
        - containers
        - authelia

    - role: containers/services/vaultwarden
      become: false
      tags:
        - containers
        - vaultwarden

    - role: containers/services/photoprism
      become: false
      tags:
        - containers
        - photoprism

    - role: containers/services/nginxproxy
      become: false
      tags:
        - containers
        - nginxproxy

    - role: containers/services/guacamole
      become: false
      tags:
        - containers
        - guacamole

    - role: containers/services/calibre
      become: false
      tags:
        - containers
        - calibre

    ###
    # Post
    ###
    - role: post
      tags:
        - post
