---
- name: Get a list of containers
  delegate_to: localhost
  become: false
  find:
    paths:
      - "roles/containers/system"
      - "roles/containers/services"
    file_type: directory
    excludes: "homer"
    recurse: no
  register: containers

- name: Include all default.yml files
  include_vars:
    dir: "{{ playbook_dir }}/{{ item.path }}/defaults"
    files_matching: main.yml
    name: "{{ item.path.split('/')[-1] }}"
  with_items: "{{ containers.files }}"

- name: Empty the variables (In case the task is called twice)
  set_fact:
    web_applications: []
  when: web_applications is defined

- name: Populate the dictionary of all containers
  set_fact:
    web_applications: "{{ web_applications | default({}) | combine({ item.path.split('/')[-1]: {'logo': '/assets/tools/homer-icons/' + item.path.split('/')[-1] + '.png', 'ip_address': lookup('vars', item.path.split('/')[-1])['ip_address'] | default(''), 'name': lookup('vars', item.path.split('/')[-1])['dashboard_name'] | default(item.path.split('/')[-1] | title), 'url' : lookup('vars', item.path.split('/')[-1])['url'] | default(''), 'category': lookup('vars', item.path.split('/')[-1])['homer_category'] | default ('') }}) }}"
  with_items: "{{ containers.files }}"
