---
### Gitea

- name: Create Gitea Directory
  file:
    path: "{{ gitea_config_dir }}"
    state: directory
    mode: "0755"

- name: Installing Gitea
  docker_container:
    name: gitea
    hostname: gitea
    image: gitea/gitea:latest
    pull: true
    state: "started"
    networks:
      - name: main_network
    env:
      "USER_UID": "1000"
      "USER_GID": "1000"
      "TZ": "{{ timezone }}"
    volumes:
      - "{{ gitea_config_dir }}:/data"
    ports:
      - "{{ gitea_port_a }}:3000"
      - "{{ gitea_port_b }}:22"
    restart_policy: unless-stopped
    memory: "{{ gitea_memory }}"
    labels: flame.type=app
      flame.name=Gitea
      flame.url="http://{{ server_ip }}:{{ gitea_port_a }}"
      flame.icon=tea-outline

- name: Remove mirror directory
  become: true
  file:
    path: "{{ gitea_config_dir }}/github_mirror"
    state: absent

- name: "Clone github mirror repo"
  become: false
  git:
    repo: "https://github.com/nmasse-itix/github-mirror.git"
    dest: "{{ gitea_config_dir }}/github_mirror"
    clone: yes

- name: Install the configuration template
  become: true
  template:
    src: ./files/config.yaml.j2
    dest: "{{ gitea_config_dir }}/github_mirror/config.yaml"
    mode: 0644

- name: Compile github-mirror
  command: "go build -o github-mirror"
  args:
    chdir: "{{ gitea_config_dir }}/github_mirror"

- name: Schedule mirroring at 00:00
  cron:
    name: Scan for mirror changes
    hour: "0"
    minute: "0"
    job: "{{ gitea_config_dir }}/github_mirror/github-mirror {{ gitea_config_dir }}/github_mirror/config.yaml"
