---
### Portainer

- name: Create Portainer Directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ portainer_config_dir }}"

- name: Installing Portainer
  docker_container:
    name: portainer
    image: portainer/portainer-ce:latest
    pull: true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - "{{ portainer_config_dir }}:/data"
    ports:
      - "{{ port_portainer }}:9000"
    restart_policy: unless-stopped
    memory: "{{ portainer_memory }}"
