---
### Flame

- name: Installing Flame
  docker_container:
    name: flame
    hostname: flame
    image: "pawelmalak/flame:latest"
    pull: yes
    state: "started"
    env:
      "PASSWORD": "{{ password }}"
      "TZ": "{{ timezone }}"
    volumes:
      - "{{ flame_config_dir }}:/app/data"
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - name: main_network
    ports:
      - "{{ flame_port }}:5005"
    restart_policy: unless-stopped
    memory: "{{ flame_memory }}"
