---
### Watchtower

- name: Installing Watchtower
  docker_container:
    name: watchtower
    image: containrrr/watchtower:latest
    pull: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command: "{{ watchtower_command }}"
    restart_policy: unless-stopped
    memory: "{{ watchtower_memory }}"
