---
### Watchtower

- name: Installing Watchtower
  docker_container:
    name: watchtower
    image: containrrr/watchtower:latest
    pull: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    env:
      "WATCHTOWER_SCHEDULE": "0 0 15 * * *"
      "WATCHTOWER_CLEANUP": "true"
      "WATCHTOWER_INCLUDE_STOPPED": "true"
      "TZ": "{{ timezone }}"
    restart_policy: unless-stopped
    memory: "{{ watchtower_memory }}"
