---
### Nextcloud

# - name: Create Nextcloud Directories
#   become: true
#   file:
#     path: "{{ item }}"
#     state: directory
#     mode: "0755"
#   with_items:
#     - "{{ nextcloud_config_dir }}"
#     - "{{ nextcloud_db_dir }}"

- name: Create a nextcloud network
  docker_network:
    name: nextcloud_network

- name: Create Nextcloud database
  docker_container:
    name: nextcloud-mariadb
    hostname: nextcloud-mariadb
    image: mariadb:latest
    pull: yes
    networks:
      - name: nextcloud_network
    command: "--transaction-isolation=READ-COMMITTED --binlog-format=ROW --skip-innodb-read-only-compressed --innodb-read-only-compressed=OFF"
    state: "started"
    env:
      "USER_UID": "1000"
      "USER_GID": "1000"
      "TZ": "{{ timezone }}"
      "MARIADB_ROOT_PASSWORD": "{{ mariadb_root_password }}"
      "MARIADB_DATABASE": "nextcloud"
      "MARIADB_USER": "nextcloud"
      "MARIADB_PASSWORD": "{{ mariadb_password }}"
    volumes:
      - "{{ nextcloud_db_dir }}:/var/lib/mysql"
    restart_policy: unless-stopped
    labels: com.centurylinklabs.watchtower.enable=false

- name: Create Nextcloud redis cache
  docker_container:
    name: nextcloud-redis
    hostname: nextcloud-redis
    image: redis:alpine
    networks:
      - name: nextcloud_network
    pull: yes
    state: "started"
    restart_policy: unless-stopped

- name: Wait until db & redis containers are running
  pause:
    seconds: 10

- name: Installing Nextcloud
  docker_container:
    name: nextcloud
    hostname: nextcloud
    image: linuxserver/nextcloud:php8
    pull: true
    state: "started"
    networks:
      - name: main_network
      - name: nextcloud_network
    env:
      "USER_UID": "1000"
      "USER_GID": "1000"
      "TZ": "{{ timezone }}"
      "MARIADB_HOST": "nextcloud-mariadb"
      "MARIADB_DATABASE": "nextcloud"
      "MARIADB_USER": "nextcloud"
      "MARIADB_PASSWORD": "{{ mariadb_password }}"
      "REDIS_HOST": "nextcloud-redis"
    volumes:
      - "{{ nextcloud_config_dir }}:/config"
      - "{{ nextcloud_data_dir }}:/data"
      - "/mnt/wd-hdd:/mnt/wd-hdd"
    ports:
      - "{{ nextcloud_port }}:443"
    restart_policy: unless-stopped
    memory: "{{ nextcloud_memory }}"
    labels: flame.type=app
      flame.name=Nextcloud
      flame.url="https://{{ server_ip }}:{{ nextcloud_port }}"
      flame.icon=cloud

- name: Wait until db container is running
  pause:
    seconds: 15
# - name: Applying correct permissions to nextcloud_config_dir
#   become: true
#   file:
#     path: "{{ nextcloud_config_dir }}"
#     mode: 0755
#     recurse: true
