---
- name: Installing Bazarr
  docker_container:
    name: bazarr
    hostname: bazarr
    image: "ghcr.io/linuxserver/bazarr"
    pull: yes
    networks:
      - name: main_network
    state: "started"
    env:
      "PUID": "1000"
      "PGID": "1000"
      "TZ": "{{ timezone }}"
    volumes:
      - "{{ bazarr_config_dir }}:/config"
      - "{{ hdd2 }}/Media/Movies:/movies"
      - "{{ hdd2 }}/Media/TV:/tv"
    restart_policy: unless-stopped
    ports:
      - "{{ bazarr_port }}:6767"
    memory: "{{ bazarr_memory }}"
    labels:
      "flame.type": "application"
      "flame.name": Bazarr
      "flame.url": "{{ server_ip }}:{{ bazarr_port }}"
      "flame.icon": "subtitles"
